### ISSUE TITLE
does not appear in the script list

### ISSUE THREAD

**Issue by DiegoRRR** [KutsuyaYuki/ABG_extension#25]
I installed it and restarted, it appears as "installed", but it does not appear in the script list...

There is no error about it (I think) when starting :
```
fatal: unable to access 'https://github.com/AUTOMATIC1111/stable-diffusion-webui
.git/': Failed to connect to github.com port 443 after 79 ms: Bad access
venv "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\venv\Scripts\Py
thon.exe"
Python 3.10.6 (main, Sep 19 2022, 15:45:37) [MSC v.1933 64 bit (AMD64)]
Commit hash: ea9bd9fc7409109adcd61b897abc2c8881161256
Installing requirements for Web UI


Installing Send2Trash==1.8.0

Installing requirement for sd-webui-controlnet

loading Smart Crop reqs from D:\apps\AI\stable-diffusion-webui__automatic1111 py
thorch2\extensions\sd_smartprocess\requirements.txt
Checking Smart Crop requirements.

Launching Web UI with arguments: --xformers
D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\venv\lib\site-package
s\torchvision\transforms\functional_tensor.py:5: UserWarning: The torchvision.tr
ansforms.functional_tensor module is deprecated in 0.15 and will be **removed in
 0.17**. Please don't rely on it. You probably just need to use APIs in torchvis
ion.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Error loading script: app.py
Traceback (most recent call last):
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\modules\scrip
ts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\modules\scrip
t_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\extensions\AB
G_extension\scripts\app.py", line 21, in <module>
    model_path = huggingface_hub.hf_hub_download(
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\venv\lib\site
-packages\huggingface_hub\utils\_validators.py", line 120, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\venv\lib\site
-packages\huggingface_hub\file_download.py", line 1253, in hf_hub_download
    raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we
cannot find the requested files in the disk cache. Please try again or make sure
 your Internet connection is on.

Error loading script: simple_depthmap.py
Traceback (most recent call last):
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\modules\scrip
ts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\modules\scrip
t_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\extensions\mu
lti-subject-render\scripts\simple_depthmap.py", line 11, in <module>
    from repositories.midas.midas.dpt_depth import DPTDepthModel
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\repositories\
midas\midas\dpt_depth.py", line 5, in <module>
    from .blocks import (
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\repositories\
midas\midas\blocks.py", line 21, in <module>
    from .backbones.next_vit import (
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\repositories\
midas\midas\backbones\next_vit.py", line 8, in <module>
    file = open("./externals/Next_ViT/classification/nextvit.py", "r")
FileNotFoundError: [Errno 2] No such file or directory: './externals/Next_ViT/cl
assification/nextvit.py'

Error loading script: main.py
Traceback (most recent call last):
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\modules\scrip
ts.py", line 229, in load_scripts
    script_module = script_loading.load_module(scriptfile.path)
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\modules\scrip
t_loading.py", line 11, in load_module
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\extensions\sd
_smartprocess\scripts\main.py", line 3, in <module>
    from extensions.sd_smartprocess import smartprocess
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\extensions\sd
_smartprocess\smartprocess.py", line 15, in <module>
    from extensions.sd_smartprocess.clipinterrogator import ClipInterrogator
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\extensions\sd
_smartprocess\clipinterrogator.py", line 14, in <module>
    from models.blip import blip_decoder, BLIP_Decoder
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\repositories\
BLIP\models\blip.py", line 11, in <module>
    from models.vit import VisionTransformer, interpolate_pos_embed
  File "D:\apps\AI\stable-diffusion-webui__automatic1111 pythorch2\repositories\
BLIP\models\vit.py", line 21, in <module>
    from fairscale.nn.checkpoint.checkpoint_activations import checkpoint_wrappe
r
ModuleNotFoundError: No module named 'fairscale'

Loading weights [797a03be80] from D:\apps\AI\stable-diffusion-webui__automatic11
11 pythorch2\models\Stable-diffusion\scenery sweetMix_v15Fp16.safetensors
Creating model from config: D:\apps\AI\stable-diffusion-webui__automatic1111 pyt
horch2\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: D:\apps\AI\stable-diffusion-webui__au
tomatic1111 pythorch2\models\VAE\vae-ft-mse-840000-ema-pruned.pt
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0):
Textual inversion embeddings skipped(1): SDA768
Model loaded in 6.5s (create model: 0.8s, apply weights to model: 1.7s, apply ha
lf(): 1.4s, load VAE: 0.4s, move model to device: 0.7s, load textual inversion e
mbeddings: 1.4s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

**Comment by KutsuyaYuki** [comment]
It seems you have more issues regarding downloading.
```
fatal: unable to access 'https://github.com/AUTOMATIC1111/stable-diffusion-webui
.git/': Failed to connect to github.com port 443 after 79 ms: Bad access
```
and
```
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we
cannot find the requested files in the disk cache. Please try again or make sure
 your Internet connection is on.
```
Seems like it's unable to download *anything* (also outside my extension). Are you perhaps behind a proxy or have a VPN enabled?

**Comment by rishabh12j** [comment]
Hi,

I am not using any VPN or proxy still getting this error

Style database not found: C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\styles.csv
*** Error loading script: app.py
    Traceback (most recent call last):
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
        response = self._make_request(
                   ^^^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
        raise new_e
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
        self._validate_conn(conn)
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
        conn.connect()
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\connection.py", line 653, in connect
        sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
        ssl_sock = ssl_wrap_socket(
                   ^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
        ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
        return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Program Files\Python311\Lib\ssl.py", line 517, in wrap_socket
        return self.sslsocket_class._create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Program Files\Python311\Lib\ssl.py", line 1104, in _create
        self.do_handshake()
      File "C:\Program Files\Python311\Lib\ssl.py", line 1382, in do_handshake
        self._sslobj.do_handshake()
    ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\requests\adapters.py", line 486, in send
        resp = conn.urlopen(
               ^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
        retries = retries.increment(
                  ^^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\util\retry.py", line 470, in increment
        raise reraise(type(error), error, _stacktrace)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\util\util.py", line 38, in reraise
        raise value.with_traceback(tb)
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
        response = self._make_request(
                   ^^^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
        raise new_e
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
        self._validate_conn(conn)
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
        conn.connect()
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\connection.py", line 653, in connect
        sock_and_verified = _ssl_wrap_socket_and_match_hostname(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
        ssl_sock = ssl_wrap_socket(
                   ^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
        ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
        return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Program Files\Python311\Lib\ssl.py", line 517, in wrap_socket
        return self.sslsocket_class._create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Program Files\Python311\Lib\ssl.py", line 1104, in _create
        self.do_handshake()
      File "C:\Program Files\Python311\Lib\ssl.py", line 1382, in do_handshake
        self._sslobj.do_handshake()
    urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\huggingface_hub\file_download.py", line 1238, in hf_hub_download
        metadata = get_hf_file_metadata(
                   ^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
        return fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\huggingface_hub\file_download.py", line 1631, in get_hf_file_metadata
        r = _request_wrapper(
            ^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\huggingface_hub\file_download.py", line 385, in _request_wrapper
        response = _request_wrapper(
                   ^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\huggingface_hub\file_download.py", line 408, in _request_wrapper
        response = get_session().request(method=method, url=url, **params)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\requests\sessions.py", line 589, in request
        resp = self.send(prep, **send_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\requests\sessions.py", line 703, in send
        r = adapter.send(request, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\huggingface_hub\utils\_http.py", line 67, in send
        return super().send(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\requests\adapters.py", line 501, in send
        raise ConnectionError(err, request=request)
    requests.exceptions.ConnectionError: (ProtocolError('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)), '(Request ID: 1a38b4b8-ff8b-43ad-98aa-b897b9229ef8)')

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\scripts.py", line 469, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 940, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\extensions\ABG_extension\scripts\app.py", line 21, in <module>
        model_path = huggingface_hub.hf_hub_download(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\huggingface_hub\utils\_validators.py", line 118, in _inner_fn
        return fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
      File "C:\Users\risha\stable-diffusion-webui-master\stable-diffusion-webui-master\venv\Lib\site-packages\huggingface_hub\file_download.py", line 1371, in hf_hub_download
        raise LocalEntryNotFoundError(
    huggingface_hub.utils._errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.
