### ISSUE TITLE
TypeError: Script.run() missing 5 required positional arguments: 'only_save_background_free_pictures', 'do_not_auto_save', 'custom_background', 'custom_background_color', and 'custom_background_random'

### ISSUE THREAD

**Issue by RuiRC** [KutsuyaYuki/ABG_extension#28]
*** Error completing request
*** Arguments: ('task(fesc5jcwog30nry)', 0, '', '', [], <PIL.Image.Image image mode=RGBA size=498x280 at 0x287E1EA7610>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 2, 1.5, 0.1, -1.0, -1.0, 0, 0, 0, False, 0, 512, 512, 1, 0, 0, 32, 0, 'S:\\ffffff-ezgif-5-28bf53fe56-gif-jpg', 'S:\\ffffff-ezgif-5-28bf53fe56-gif-jpg\\Out', '', [], 9, False, False, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, 'LoRA', 'None', 1, 1, None, 'Refresh models', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000287C5B52410>, None, '', 'Get Tags', '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, True, False, False, '#000000', False, None, None, False, 50, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 0, True, 0, False, 8, 0, 0, 2048, 2048, 2) {}
    Traceback (most recent call last):
      File "S:\Servidor\stable-diffusion-webui\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "S:\Servidor\stable-diffusion-webui\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "S:\Servidor\stable-diffusion-webui\modules\img2img.py", line 196, in img2img
        processed = modules.scripts.scripts_img2img.run(p, *args)
      File "S:\Servidor\stable-diffusion-webui\modules\scripts.py", line 456, in run
        processed = script.run(p, *script_args)
    TypeError: Script.run() missing 5 required positional arguments: 'only_save_background_free_pictures', 'do_not_auto_save', 'custom_background', 'custom_background_color', and 'custom_background_random'

---

**Comment by WaterForLiquid** [comment]
nothing? im dealing with this too

**Comment by notds** [comment]
same :(
