### ISSUE TITLE
RuntimeError onnxruntime

### ISSUE THREAD

**Issue by coronet1127** [KutsuyaYuki/ABG_extension#4]
Error loading script: app.py
Traceback (most recent call last):
  File "C:\Users\coron\OneDrive\デスクトップ\stable diffusion\stable-diffusion-webui\modules\scripts.py", line 205, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "C:\Users\coron\OneDrive\デスクトップ\stable diffusion\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "C:\Users\coron\OneDrive\デスクトップ\stable diffusion\stable-diffusion-webui\extensions\ABG_extension\scripts\app.py", line 18, in <module>
    rmbg_model = rt.InferenceSession(model_path, providers=providers)
  File "C:\Users\coron\OneDrive\デスクトップ\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 347, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\coron\OneDrive\デスクトップ\stable diffusion\stable-diffusion-webui\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 395, in _create_inference_session
    sess.initialize_session(providers, provider_options, disabled_optimizers)
RuntimeError: D:\a\_work\1\s\onnxruntime\python\onnxruntime_pybind_state.cc:574 onnxruntime::python::CreateExecutionProviderInstance CUDA_PATH is set but CUDA wasn't able to be loaded. Please install the correct version of CUDA and cuDNN as mentioned in the GPU requirements page (https://onnxruntime.ai/docs/reference/execution-providers/CUDA-ExecutionProvider.html#requirements), make sure they're in the PATH, and that your GPU is supported.

**Comment by KutsuyaYuki** [comment]
Can you provide more information?

* What gpu do you have?
* Did you check the instructions in the error message? 
* Why is this running from a Onedrive folder in a Japanese name folder, that's like asking for problems.

**Comment by coronet1127** [comment]
thanks!
It was caused by a デスクトップ in OneDrive.
I moved it to the C drive under the name desktop and was able to run it.
