### ISSUE TITLE
ValueError: could not broadcast input array from shape (1024,1024,4) into shape (1024,1024,3)

### ISSUE THREAD

**Issue by gembleman** [KutsuyaYuki/ABG_extension#8]
Arguments: ('task(mxoj4dl0g6k95x3)', 0, '', '', ['01'], <PIL.Image.Image image mode=RGBA size=1280x1020 at 0x1E58BCE1120>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, 0, 32, 0, '', '', '', [], 9, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, False) {}
Traceback (most recent call last):
  File "C:\Users\jjj\Desktop\GrimAI_test\stable-diffusion-webui\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\jjj\Desktop\GrimAI_test\stable-diffusion-webui\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\jjj\Desktop\GrimAI_test\stable-diffusion-webui\modules\img2img.py", line 166, in img2img
    processed = modules.scripts.scripts_img2img.run(p, *args)
  File "C:\Users\jjj\Desktop\GrimAI_test\stable-diffusion-webui\modules\scripts.py", line 376, in run
    processed = script.run(p, *script_args)
  File "C:\Users\jjj\Desktop\GrimAI_test\stable-diffusion-webui\extensions\ABG_extension\scripts\app.py", line 100, in run
    nmask, nimg = rmbg_fn(np.array(proc.images[i]))
  File "C:\Users\jjj\Desktop\GrimAI_test\stable-diffusion-webui\extensions\ABG_extension\scripts\app.py", line 61, in rmbg_fn
    mask = get_mask(img)
  File "C:\Users\jjj\Desktop\GrimAI_test\stable-diffusion-webui\extensions\ABG_extension\scripts\app.py", line 41, in get_mask
    img_input[ph // 2:ph // 2 + h, pw //
ValueError: could not broadcast input array from shape (1024,1024,4) into shape (1024,1024,3)

This bug occurs when I use the img2img function.

**Comment by mlc3141** [comment]
Same error here. Have you found a workaround?

**Comment by KutsuyaYuki** [comment]
Are you using a JPEG? The WebUI can't change the output format currently. There is an open issue on the 1111 repo.

**Comment by KutsuyaYuki** [comment]
hey @gembleman. Why are you using that file? What background are you trying to remove from it? This plugin is mainly meant for humanoids/anime. And besides that, your picture is already transparent.

**Comment by sedetweiler** [comment]
Same error.  I need to find another solution if we are all stuck in the same place.

**Comment by KutsuyaYuki** [comment]
I have attempted to fix the issue. I cannot reproduce it myself, but this should at least work around the exception you are getting.

**Comment by KutsuyaYuki** [comment]
Closed because no further response
